# Generated by Django 5.2.2 on 2025-06-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del estado de la reserva')),
                ('estado', models.CharField(max_length=45, verbose_name='Estado de la reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la mesa')),
                ('numero', models.CharField(max_length=45, verbose_name='Número de la mesa')),
                ('piso', models.IntegerField(blank=True, null=True, verbose_name='Piso de la mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del tipo de rol')),
                ('rol', models.CharField(max_length=45, verbose_name='Nombre del rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del usuario')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo del usuario')),
                ('foto', models.TextField(blank=True, max_length=150, null=True, verbose_name='URL del perfil del usuario')),
                ('contrasena', models.CharField(max_length=45, verbose_name='Contraseña del usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.rol', verbose_name='Rol del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la reserva')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateTimeField(verbose_name='Fecha final')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de la reserva')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.estadoreserva', verbose_name='Estado de la reserva')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.mesa', verbose_name='Mesa reservada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario', verbose_name='Usuario que reserva')),
            ],
        ),
    ]
